#!/bin/bash
set -euo pipefail
[ "${PFB_DEBUG}" -eq "1" ] && set -x

CORES=$(python -c "import multiprocessing; print(multiprocessing.cpu_count());")
HWMEMSIZE=$(sysctl -n hw.memsize)
MEMORY_MB=$((HWMEMSIZE / 1024 ** 2))

# Set configuration parameters.
psql <<EOF
-- Generated by PGConfig 3.1.0 (1d600ea0d1d79f13dd7ed686f9e2befc1fcf9226)
-- https://api.pgconfig.org/v1/tuning/get-config?format=alter_system&&log_format=csvlog&max_connections=100&pg_version=13&environment_name=WEB&total_ram=32GB&cpus=8&drive_type=SSD&arch=x86-64&os_type=linux

-- Memory Configuration
ALTER SYSTEM SET shared_buffers TO '$((MEMORY_MB / 4))MB';
ALTER SYSTEM SET effective_cache_size TO '$((3 * MEMORY_MB / 4))MB';
ALTER SYSTEM SET work_mem TO '$((8 * MEMORY_MB / 1024))MB';
ALTER SYSTEM SET maintenance_work_mem TO '$((MEMORY_MB / 16))MB';

-- Checkpoint Related Configuration
ALTER SYSTEM SET min_wal_size TO '$((MEMORY_MB / 8))MB';
ALTER SYSTEM SET max_wal_size TO '$((MEMORY_MB / 2))MB';
ALTER SYSTEM SET checkpoint_completion_target TO '0.9';
ALTER SYSTEM SET wal_buffers TO '-1';

-- Network Related Configuration
ALTER SYSTEM SET listen_addresses TO '*';
ALTER SYSTEM SET max_connections TO '100';

-- Storage Configuration
ALTER SYSTEM SET random_page_cost TO '1.1';
ALTER SYSTEM SET effective_io_concurrency TO '200';

-- Worker Processes Configuration
ALTER SYSTEM SET max_worker_processes TO '${CORES}';
ALTER SYSTEM SET max_parallel_workers TO '${CORES}';
ALTER SYSTEM SET max_parallel_workers_per_gather TO '$((CORES / 2))';
ALTER SYSTEM SET max_parallel_maintenance_workers TO '$((CORES / 2))';
EOF

# Install extensions.
psql <<EOF
CREATE EXTENSION "uuid-ossp";
CREATE EXTENSION "hstore";
CREATE EXTENSION "plpython3u";
CREATE EXTENSION "pgrouting";
CREATE SCHEMA IF NOT EXISTS generated AUTHORIZATION ${PGUSER};
CREATE SCHEMA IF NOT EXISTS received AUTHORIZATION ${PGUSER};
CREATE SCHEMA IF NOT EXISTS scratch AUTHORIZATION ${PGUSER};
ALTER USER ${PGUSER} SET search_path TO generated,received,scratch,"\$user",public;
EOF
